enable:
  issues: false
  prs: true

labels:
  "review needed":
    include:
      - ""
    exclude:
      - "to master"
      - "to pre-production"
      - "to production"
  "bugfix":
    include:
      - "fix"
      - "Fix"
  "test":
    include:
      - "test"
      - "Test"
  "feature":
    include:
      - "feat"
      - "Feat"
  "documentation":
    include:
      - "docs"
      - "Docs"
  "refactor":
    include:
      - "refactor"
      - "Refactor"
  "chore":
    include:
      - "chore"
      - "Chore"
