enable:
  issues: false
  prs: true

comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

labels:
  "review needed":
    include:
      - ""
  "bugfix":
    include:
      - '\bfix\b'
  "test":
    include:
      - '\btest\b'
  "feature":
    include:
      - '\bfeat\b'
  "documentation":
    include:
      - '\bdocs\b'
  "refactor":
    include:
      - '\brefactor\b'
  "chore":
    include:
      - '\bchore\b'
