name: review labeler

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT_FOR_AUTOMATION }}

      - name: Add or remove labels based on review
        run: |
          REVIEW_STATE="${{ github.event.review.state }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          APPROVALS=$(gh pr view $PR_NUMBER --json reviews --jq '.reviews | group_by(.author.login) | map(max_by(.submittedAt)) | map(select(.state == "APPROVED")) | length')
          REQUEST_CHANGES=$(gh pr view $PR_NUMBER --json reviews --jq '.reviews | group_by(.author.login) | map(max_by(.submittedAt)) | map(select(.state == "CHANGES_REQUESTED")) | length')

            echo "Review State: $REVIEW_STATE"
            echo "PR Number: $PR_NUMBER"
            echo "Approvals: $APPROVALS"
            echo "Request Changes: $REQUEST_CHANGES"

          if [[ "$REVIEW_STATE" == "commented" ]]; then
            gh pr edit $PR_NUMBER --add-label "answer needed"
          fi

          if [[ "$REVIEW_STATE" == "changes_requested" ]]; then
            gh pr edit $PR_NUMBER --add-label "answer needed" --remove-label "merge needed"
          fi

          if [[ "$APPROVALS" -ge 1 && "$REQUEST_CHANGES" -eq 0 ]]; then
            gh pr edit $PR_NUMBER --remove-label "review needed" --add-label "merge needed"
          fi

        env:
          GH_TOKEN: ${{ secrets.PAT_FOR_AUTOMATION }}

      - name: Remove "answer needed" label if all conversations are resolved
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          RESOLVED_CONVERSATIONS=$(gh pr view $PR_NUMBER --json comments --jq '.comments | map(select(.isResolved == true)) | length')
          TOTAL_CONVERSATIONS=$(gh pr view $PR_NUMBER --json comments --jq '.comments | length')

          echo "Resolved Conversations: $RESOLVED_CONVERSATIONS"
          echo "Total Conversations: $TOTAL_CONVERSATIONS"

          if [[ "$RESOLVED_CONVERSATIONS" -eq "$TOTAL_CONVERSATIONS" && "$TOTAL_CONVERSATIONS" -gt 0 ]]; then
            echo "All conversations are resolved. Removing 'answer needed' label."
            gh pr edit $PR_NUMBER --remove-label "answer needed"
          fi

        env:
          GH_TOKEN: ${{ secrets.PAT_FOR_AUTOMATION }}
